name: Build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

      # Checkout the code.
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

      # Install the dependencies: ARM's GCC toolchain.
    - name: Install dependencies
      uses: turtlesec-no/get-arm-toolchain@main

      # Compile the code.
    - name: Compile
      run: make
